### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by pinkfloydFR** [Aadityajoshi151/Elysian#54]
When i try to upload my bookmarks from latest brave version , got this error 👍 
```
PayloadTooLargeError: request entity too large
    at readStream (/Elysian/node_modules/raw-body/index.js:163:17)
    at getRawBody (/Elysian/node_modules/raw-body/index.js:116:12)
    at read (/Elysian/node_modules/body-parser/lib/read.js:79:3)
    at jsonParser (/Elysian/node_modules/body-parser/lib/types/json.js:138:5)
    at Layer.handle [as handle_request] (/Elysian/node_modules/express/lib/router/layer.js:95:5)
    at next (/Elysian/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/Elysian/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/Elysian/node_modules/express/lib/router/layer.js:95:5)
    at /Elysian/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Elysian/node_modules/express/lib/router/index.js:346:12)
```

Config : 
```
services:
  elysian:
    image: aadityajoshi151/elysian:latest
    container_name: elysian
    privileged: true
    environment:
      - API_KEY=*****
      - PUID=1042
      - PGID=1042
      - TZ=Europe/Paris
#    ports:
#      - 6161:6161
    volumes:
      - ./data:/Elysian/src/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.elysian.rule=Host(`link.***.com`)
      - traefik.http.routers.elysian.entrypoints=websecure
      - traefik.http.routers.elysian.service=elysian
      - traefik.http.routers.elysian.tls=true
      - traefik.http.routers.elysian.middlewares=my-geoblock@file,sslheader@docker
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.services.elysian.loadbalancer.server.port=6161
    networks:
      elysian:
      traefik:

networks:
  elysian:
    name: elysian
    driver_opts:
      com.docker.network.bridge.name: br-elysian
  traefik:
    external: true

```

data  folder is empty fyi.

Thanks !
